version: '3'
services:
  node:
    image: node
    volumes:
      - ./bitcore-wallet:/var/www/html/bitcore-wallet
    command: bash -c "cd /var/www/html/bitcore-wallet && npm install"
    environment:
      - BWS_HOST=http://localhost:3232
